In [3]:
# imports
import pandas as pd
import requests
import zipfile
import io
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import load_breast_cancer
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import torch
import torch.nn as nn
import torch.optim as optim
from torch.optim.lr_scheduler import StepLR
from torch.utils.data import DataLoader, TensorDataset

For this example we will be using the Concrete Compressive Strength Dataset: https://archive.ics.uci.edu/dataset/165/concrete+compressive+strength

In [4]:
# URL to the concrete+compressive+strength.zip file on the UCI archive
concrete_zip_url = "https://archive.ics.uci.edu/static/public/165/concrete+compressive+strength.zip"

# Download the zip file
response = requests.get(concrete_zip_url)
response.raise_for_status() # Raise an exception for bad status codes

# Read the zip file from memory
with zipfile.ZipFile(io.BytesIO(response.content)) as z:
    # Print all file names in the zip archive to identify the correct one

    # Use the correct Excel file name identified from z.namelist()
    with z.open('Concrete_Data.xls') as excel_file:
        concrete_df = pd.read_excel(excel_file)

# create X and y, scale data, create train and test
target_column_name = concrete_df.columns[-1]
y = concrete_df[target_column_name]
X = concrete_df.drop(target_column_name, axis=1)

scaler = StandardScaler()
X = pd.DataFrame(scaler.fit_transform(X).astype(np.float32))
y = pd.DataFrame(y.astype(np.float32))

# train / val split
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=499)
# NOTE: I haven't used a test set in this example because it's all about learning!

display(X_train.head())
display(y_train.head())

,0,1,2,3,4,5,6,7
316,-0.281032,-0.856886,0.715275,-1.659688,1.029528,0.425670,1.574577,-0.279733
554,-0.411326,0.984546,-0.847132,0.193657,-1.038944,0.870881,-0.490150,-0.612331
663,-1.418445,1.462298,-0.847132,0.488805,-1.038944,-0.585704,0.818867,-0.279733
881,-1.226977,0.824522,0.919448,-0.167080,0.300957,0.374201,-1.055435,-0.279733
774,0.965325,-0.856886,-0.847132,0.207711,-1.038944,1.776742,0.130042,-0.612331

     Concrete compressive strength(MPa, megapascals)
316                                         33.942902
554                                         15.691094
663                                         27.874825
881                                         25.558876
774                                         11.465986

In [5]:
class FCNN(nn.Module):
  def __init__(self, input_size):
    super(FCNN, self).__init__()
    self.fc1 = nn.Linear(input_size, 32)
    self.fc2 = nn.Linear(32, 16)
    self.fc3 = nn.Linear(16, 1)
    self.relu = nn.ReLU()

  def forward(self, x):
    x = self.fc1(x)
    x = self.relu(x)
    x = self.fc2(x)
    x = self.relu(x)
    return self.fc3(x)

In [6]:
# Initialize the models we defined above
model = FCNN(input_size=X_train.shape[1])

# To use mini-batch GD we need to create a Dataset object
X_train_torch = torch.tensor(X_train.values, dtype=torch.float32)
y_train_torch = torch.tensor(y_train.values, dtype=torch.float32).view(-1, 1)
X_val_torch = torch.tensor(X_val.values, dtype=torch.float32)
y_val_torch = torch.tensor(y_val.values, dtype=torch.float32).view(-1, 1)
# Wrap them in a Dataset
train_dataset = TensorDataset(X_train_torch, y_train_torch)
val_dataset = TensorDataset(X_val_torch, y_val_torch)
# Now create a DataLoader for Mini-Batch GD
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=32, shuffle=False)

# Define our Loss function and algorithm for optimization (aka our 'Optimizer')
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=1e-3)

# training loop
epochs = 5_000

for epoch in range(epochs):

    # --- TRAINING PHASE ---
    model.train() # Set to training mode
    train_loss = 0
    for data, target in train_loader:
        optimizer.zero_grad()
        output = model(data)
        loss = criterion(output, target)
        loss.backward()
        optimizer.step()
        train_loss += loss.item()
        if (epoch + 1) % 50 == 0:
            print(f"Epoch {epoch + 1}/{epochs} | Batch Loss: {loss.item():.4f}")


    # --- VALIDATION PHASE ---
    model.eval() # Set to evaluation mode (turns off Dropout, BatchNorm, etc.)
    val_loss = 0
    with torch.no_grad(): # Disables gradient calculation
        for data, target in val_loader:
            output = model(data)
            loss = criterion(output, target)
            val_loss += loss.item()

    if (epoch + 1) % 50 == 0:
        with torch.no_grad():
            # Calculate average losses
            avg_train = train_loss / len(train_loader)
            avg_val = val_loss / len(val_loader)

            print()
            print(f"Epoch {epoch + 1}: Train Loss: {avg_train:.4f} | Val Loss: {avg_val:.4f}")
            print("-----------------------")
            print()

/Users/itzjuztmya/miniconda3/envs/school/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Epoch 50/5000 | Batch Loss: 32.1468
Epoch 50/5000 | Batch Loss: 53.0054
Epoch 50/5000 | Batch Loss: 20.8579
Epoch 50/5000 | Batch Loss: 19.4361
Epoch 50/5000 | Batch Loss: 19.7885
Epoch 50/5000 | Batch Loss: 44.0386
Epoch 50/5000 | Batch Loss: 25.4222
Epoch 50/5000 | Batch Loss: 36.8699
Epoch 50/5000 | Batch Loss: 28.2453
Epoch 50/5000 | Batch Loss: 38.0798
Epoch 50/5000 | Batch Loss: 30.8794
Epoch 50/5000 | Batch Loss: 24.9965
Epoch 50/5000 | Batch Loss: 39.0789
Epoch 50/5000 | Batch Loss: 31.3440
Epoch 50/5000 | Batch Loss: 40.4970
Epoch 50/5000 | Batch Loss: 14.7864
Epoch 50/5000 | Batch Loss: 53.3200
Epoch 50/5000 | Batch Loss: 49.1580
Epoch 50/5000 | Batch Loss: 25.9079
Epoch 50/5000 | Batch Loss: 24.3183
Epoch 50/5000 | Batch Loss: 35.7443
Epoch 50/5000 | Batch Loss: 49.2896
Epoch 50/5000 | Batch Loss: 27.1995
Epoch 50/5000 | Batch Loss: 25.7273
Epoch 50/5000 | Batch Loss: 36.1528
Epoch 50/5000 | Batch Loss: 43.7029

Epoch 50: Train Loss: 33.4613 | Val Loss: 43.6684
-----------------------

Epoch 100/5000 | Batch Loss: 16.4869
Epoch 100/5000 | Batch Loss: 15.3464
Epoch 100/5000 | Batch Loss: 24.0175
Epoch 100/5000 | Batch Loss: 18.5487
Epoch 100/5000 | Batch Loss: 22.6766
Epoch 100/5000 | Batch Loss: 19.5038
Epoch 100/5000 | Batch Loss: 43.3949
Epoch 100/5000 | Batch Loss: 36.1130
Epoch 100/5000 | Batch Loss: 22.5492
Epoch 100/5000 | Batch Loss: 17.8038
Epoch 100/5000 | Batch Loss: 19.2702
Epoch 100/5000 | Batch Loss: 24.5811
Epoch 100/5000 | Batch Loss: 30.3856
Epoch 100/5000 | Batch Loss: 33.2904
Epoch 100/5000 | Batch Loss: 19.0123
Epoch 100/5000 | Batch Loss: 24.9449
Epoch 100/5000 | Batch Loss: 18.4361
Epoch 100/5000 | Batch Loss: 27.3594
Epoch 100/5000 | Batch Loss: 23.5024
Epoch 100/5000 | Batch Loss: 24.8214
Epoch 100/5000 | Batch Loss: 39.5717
Epoch 100/5000 | Batch Loss: 24.5767
Epoch 100/5000 | Batch Loss: 40.1562
Epoch 100/5000 | Batch Loss: 31.1123
Epoch 100/5000 | Batch Loss: 22.1253
Epoch 100/5000 | Batch Loss: 26.5156

Epoch 100: Train Loss: 25.6193 | Val Loss: 39.4448
-----------------------

Epoch 150/5000 | Batch Loss: 16.5499
Epoch 150/5000 | Batch Loss: 12.7108
Epoch 150/5000 | Batch Loss: 9.7037
Epoch 150/5000 | Batch Loss: 27.3099
Epoch 150/5000 | Batch Loss: 14.7934
Epoch 150/5000 | Batch Loss: 23.3094
Epoch 150/5000 | Batch Loss: 26.0581
Epoch 150/5000 | Batch Loss: 36.9260
Epoch 150/5000 | Batch Loss: 17.1675
Epoch 150/5000 | Batch Loss: 18.0672
Epoch 150/5000 | Batch Loss: 14.4382
Epoch 150/5000 | Batch Loss: 15.3282
Epoch 150/5000 | Batch Loss: 36.9090
Epoch 150/5000 | Batch Loss: 35.9492
Epoch 150/5000 | Batch Loss: 19.4617
Epoch 150/5000 | Batch Loss: 21.2247
Epoch 150/5000 | Batch Loss: 20.6449
Epoch 150/5000 | Batch Loss: 9.7748
Epoch 150/5000 | Batch Loss: 21.8079
Epoch 150/5000 | Batch Loss: 22.2437
Epoch 150/5000 | Batch Loss: 33.4863
Epoch 150/5000 | Batch Loss: 15.8495
Epoch 150/5000 | Batch Loss: 23.7662
Epoch 150/5000 | Batch Loss: 27.0047
Epoch 150/5000 | Batch Loss: 19.3180
Epoch 150/5000 | Batch Loss: 19.8869

Epoch 150: Train Loss: 21.5265 | Val Loss: 38.8451
-----------------------

Epoch 200/5000 | Batch Loss: 24.4151
Epoch 200/5000 | Batch Loss: 15.2240
Epoch 200/5000 | Batch Loss: 9.8687
Epoch 200/5000 | Batch Loss: 23.4225
Epoch 200/5000 | Batch Loss: 9.8896
Epoch 200/5000 | Batch Loss: 22.3137
Epoch 200/5000 | Batch Loss: 23.9815
Epoch 200/5000 | Batch Loss: 19.3100
Epoch 200/5000 | Batch Loss: 22.2737
Epoch 200/5000 | Batch Loss: 15.2788
Epoch 200/5000 | Batch Loss: 16.4795
Epoch 200/5000 | Batch Loss: 20.2603
Epoch 200/5000 | Batch Loss: 20.9300
Epoch 200/5000 | Batch Loss: 11.6743
Epoch 200/5000 | Batch Loss: 10.9824
Epoch 200/5000 | Batch Loss: 27.2944
Epoch 200/5000 | Batch Loss: 21.8070
Epoch 200/5000 | Batch Loss: 38.7025
Epoch 200/5000 | Batch Loss: 23.4896
Epoch 200/5000 | Batch Loss: 15.7429
Epoch 200/5000 | Batch Loss: 30.3705
Epoch 200/5000 | Batch Loss: 25.5538
Epoch 200/5000 | Batch Loss: 10.5344
Epoch 200/5000 | Batch Loss: 20.8912
Epoch 200/5000 | Batch Loss: 20.6320
Epoch 200/5000 | Batch Loss: 26.9947

Epoch 200: Train Loss: 20.3199 | Val Loss: 37.3233
-----------------------

Epoch 250/5000 | Batch Loss: 29.3342
Epoch 250/5000 | Batch Loss: 26.6227
Epoch 250/5000 | Batch Loss: 23.6198
Epoch 250/5000 | Batch Loss: 18.8228
Epoch 250/5000 | Batch Loss: 14.1516
Epoch 250/5000 | Batch Loss: 23.6119
Epoch 250/5000 | Batch Loss: 14.6276
Epoch 250/5000 | Batch Loss: 16.1488
Epoch 250/5000 | Batch Loss: 18.0232
Epoch 250/5000 | Batch Loss: 23.1912
Epoch 250/5000 | Batch Loss: 13.0780
Epoch 250/5000 | Batch Loss: 12.3206
Epoch 250/5000 | Batch Loss: 14.8396
Epoch 250/5000 | Batch Loss: 14.7424
Epoch 250/5000 | Batch Loss: 12.8062
Epoch 250/5000 | Batch Loss: 29.6159
Epoch 250/5000 | Batch Loss: 21.9228
Epoch 250/5000 | Batch Loss: 13.4540
Epoch 250/5000 | Batch Loss: 18.1222
Epoch 250/5000 | Batch Loss: 8.1839
Epoch 250/5000 | Batch Loss: 15.2933
Epoch 250/5000 | Batch Loss: 12.6290
Epoch 250/5000 | Batch Loss: 9.9436
Epoch 250/5000 | Batch Loss: 18.6392
Epoch 250/5000 | Batch Loss: 25.5064
Epoch 250/5000 | Batch Loss: 28.3055

Epoch 250: Train Loss: 18.3676 | Val Loss: 33.0841
-----------------------

Epoch 300/5000 | Batch Loss: 13.9756
Epoch 300/5000 | Batch Loss: 15.9563
Epoch 300/5000 | Batch Loss: 7.8487
Epoch 300/5000 | Batch Loss: 15.3400
Epoch 300/5000 | Batch Loss: 14.2956
Epoch 300/5000 | Batch Loss: 11.6209
Epoch 300/5000 | Batch Loss: 19.7960
Epoch 300/5000 | Batch Loss: 26.9844
Epoch 300/5000 | Batch Loss: 16.3050
Epoch 300/5000 | Batch Loss: 21.7643
Epoch 300/5000 | Batch Loss: 10.6553
Epoch 300/5000 | Batch Loss: 20.6256
Epoch 300/5000 | Batch Loss: 32.6881
Epoch 300/5000 | Batch Loss: 15.0496
Epoch 300/5000 | Batch Loss: 15.4537
Epoch 300/5000 | Batch Loss: 16.2912
Epoch 300/5000 | Batch Loss: 21.7431
Epoch 300/5000 | Batch Loss: 16.9402
Epoch 300/5000 | Batch Loss: 20.9600
Epoch 300/5000 | Batch Loss: 9.0192
Epoch 300/5000 | Batch Loss: 11.0476
Epoch 300/5000 | Batch Loss: 17.8680
Epoch 300/5000 | Batch Loss: 10.7783
Epoch 300/5000 | Batch Loss: 7.8536
Epoch 300/5000 | Batch Loss: 13.4464
Epoch 300/5000 | Batch Loss: 14.2997

Epoch 300: Train Loss: 16.1002 | Val Loss: 34.2666
-----------------------

Epoch 350/5000 | Batch Loss: 19.1899
Epoch 350/5000 | Batch Loss: 10.1941
Epoch 350/5000 | Batch Loss: 12.2246
Epoch 350/5000 | Batch Loss: 14.2161
Epoch 350/5000 | Batch Loss: 12.7134
Epoch 350/5000 | Batch Loss: 20.7392
Epoch 350/5000 | Batch Loss: 9.5867
Epoch 350/5000 | Batch Loss: 9.9729
Epoch 350/5000 | Batch Loss: 14.1366
Epoch 350/5000 | Batch Loss: 15.0390
Epoch 350/5000 | Batch Loss: 5.1491
Epoch 350/5000 | Batch Loss: 20.8861
Epoch 350/5000 | Batch Loss: 9.4013
Epoch 350/5000 | Batch Loss: 13.1344
Epoch 350/5000 | Batch Loss: 28.4414
Epoch 350/5000 | Batch Loss: 11.9693
Epoch 350/5000 | Batch Loss: 13.9064
Epoch 350/5000 | Batch Loss: 7.8271
Epoch 350/5000 | Batch Loss: 10.3017
Epoch 350/5000 | Batch Loss: 18.5047
Epoch 350/5000 | Batch Loss: 22.3314
Epoch 350/5000 | Batch Loss: 12.3302
Epoch 350/5000 | Batch Loss: 13.0313
Epoch 350/5000 | Batch Loss: 6.9230
Epoch 350/5000 | Batch Loss: 7.7859
Epoch 350/5000 | Batch Loss: 7.0155

Epoch 350: Train Loss: 13.3443 | Val Loss: 35.1931
-----------------------

Epoch 400/5000 | Batch Loss: 17.9801
Epoch 400/5000 | Batch Loss: 16.6931
Epoch 400/5000 | Batch Loss: 28.5473
Epoch 400/5000 | Batch Loss: 6.9756
Epoch 400/5000 | Batch Loss: 11.6521
Epoch 400/5000 | Batch Loss: 8.6344
Epoch 400/5000 | Batch Loss: 10.9711
Epoch 400/5000 | Batch Loss: 18.4984
Epoch 400/5000 | Batch Loss: 25.5236
Epoch 400/5000 | Batch Loss: 10.3748
Epoch 400/5000 | Batch Loss: 10.7624
Epoch 400/5000 | Batch Loss: 16.3052
Epoch 400/5000 | Batch Loss: 12.1635
Epoch 400/5000 | Batch Loss: 14.2824
Epoch 400/5000 | Batch Loss: 10.8429
Epoch 400/5000 | Batch Loss: 17.2682
Epoch 400/5000 | Batch Loss: 13.5640
Epoch 400/5000 | Batch Loss: 14.5826
Epoch 400/5000 | Batch Loss: 11.8590
Epoch 400/5000 | Batch Loss: 14.5872
Epoch 400/5000 | Batch Loss: 7.0969
Epoch 400/5000 | Batch Loss: 13.6836
Epoch 400/5000 | Batch Loss: 13.3558
Epoch 400/5000 | Batch Loss: 11.5316
Epoch 400/5000 | Batch Loss: 15.9906
Epoch 400/5000 | Batch Loss: 12.4563

Epoch 400: Train Loss: 14.0839 | Val Loss: 29.2908
-----------------------

Epoch 450/5000 | Batch Loss: 14.9929
Epoch 450/5000 | Batch Loss: 13.5426
Epoch 450/5000 | Batch Loss: 13.8429
Epoch 450/5000 | Batch Loss: 9.1730
Epoch 450/5000 | Batch Loss: 7.5492
Epoch 450/5000 | Batch Loss: 15.7896
Epoch 450/5000 | Batch Loss: 12.1405
Epoch 450/5000 | Batch Loss: 26.6289
Epoch 450/5000 | Batch Loss: 12.4353
Epoch 450/5000 | Batch Loss: 9.9767
Epoch 450/5000 | Batch Loss: 12.6149
Epoch 450/5000 | Batch Loss: 10.2909
Epoch 450/5000 | Batch Loss: 17.8669
Epoch 450/5000 | Batch Loss: 18.0173
Epoch 450/5000 | Batch Loss: 12.5526
Epoch 450/5000 | Batch Loss: 11.2895
Epoch 450/5000 | Batch Loss: 12.9798
Epoch 450/5000 | Batch Loss: 15.2837
Epoch 450/5000 | Batch Loss: 7.1310
Epoch 450/5000 | Batch Loss: 8.6357
Epoch 450/5000 | Batch Loss: 9.2850
Epoch 450/5000 | Batch Loss: 7.2514
Epoch 450/5000 | Batch Loss: 8.7746
Epoch 450/5000 | Batch Loss: 12.6141
Epoch 450/5000 | Batch Loss: 11.4210
Epoch 450/5000 | Batch Loss: 6.9304

Epoch 450: Train Loss: 12.2696 | Val Loss: 33.7227
-----------------------

Epoch 500/5000 | Batch Loss: 16.3341
Epoch 500/5000 | Batch Loss: 21.8527
Epoch 500/5000 | Batch Loss: 13.1360
Epoch 500/5000 | Batch Loss: 11.3466
Epoch 500/5000 | Batch Loss: 8.7720
Epoch 500/5000 | Batch Loss: 5.6995
Epoch 500/5000 | Batch Loss: 19.1310
Epoch 500/5000 | Batch Loss: 10.5518
Epoch 500/5000 | Batch Loss: 8.3680
Epoch 500/5000 | Batch Loss: 27.1712
Epoch 500/5000 | Batch Loss: 13.9712
Epoch 500/5000 | Batch Loss: 15.6870
Epoch 500/5000 | Batch Loss: 21.4686
Epoch 500/5000 | Batch Loss: 13.1205
Epoch 500/5000 | Batch Loss: 12.5120
Epoch 500/5000 | Batch Loss: 9.0887
Epoch 500/5000 | Batch Loss: 6.8691
Epoch 500/5000 | Batch Loss: 11.7750
Epoch 500/5000 | Batch Loss: 5.3638
Epoch 500/5000 | Batch Loss: 4.4696
Epoch 500/5000 | Batch Loss: 17.9679
Epoch 500/5000 | Batch Loss: 8.2660
Epoch 500/5000 | Batch Loss: 9.8556
Epoch 500/5000 | Batch Loss: 18.1714
Epoch 500/5000 | Batch Loss: 18.3074
Epoch 500/5000 | Batch Loss: 8.2611

Epoch 500: Train Loss: 12.9815 | Val Loss: 31.3136
-----------------------

Epoch 550/5000 | Batch Loss: 14.2576
Epoch 550/5000 | Batch Loss: 11.3435
Epoch 550/5000 | Batch Loss: 13.0478
Epoch 550/5000 | Batch Loss: 11.4207
Epoch 550/5000 | Batch Loss: 9.1594
Epoch 550/5000 | Batch Loss: 16.4733
Epoch 550/5000 | Batch Loss: 8.2312
Epoch 550/5000 | Batch Loss: 12.8391
Epoch 550/5000 | Batch Loss: 9.0722
Epoch 550/5000 | Batch Loss: 13.3450
Epoch 550/5000 | Batch Loss: 12.6114
Epoch 550/5000 | Batch Loss: 9.5502
Epoch 550/5000 | Batch Loss: 8.4630
Epoch 550/5000 | Batch Loss: 7.6584
Epoch 550/5000 | Batch Loss: 7.5246
Epoch 550/5000 | Batch Loss: 27.2157
Epoch 550/5000 | Batch Loss: 8.8518
Epoch 550/5000 | Batch Loss: 6.1680
Epoch 550/5000 | Batch Loss: 7.0447
Epoch 550/5000 | Batch Loss: 8.0281
Epoch 550/5000 | Batch Loss: 12.2030
Epoch 550/5000 | Batch Loss: 9.4521
Epoch 550/5000 | Batch Loss: 9.9825
Epoch 550/5000 | Batch Loss: 10.0365
Epoch 550/5000 | Batch Loss: 11.0453
Epoch 550/5000 | Batch Loss: 15.3663

Epoch 550: Train Loss: 11.1689 | Val Loss: 36.4061
-----------------------

Epoch 600/5000 | Batch Loss: 7.8725
Epoch 600/5000 | Batch Loss: 11.1799
Epoch 600/5000 | Batch Loss: 13.9748
Epoch 600/5000 | Batch Loss: 31.8789
Epoch 600/5000 | Batch Loss: 12.8064
Epoch 600/5000 | Batch Loss: 11.1433
Epoch 600/5000 | Batch Loss: 11.7498
Epoch 600/5000 | Batch Loss: 11.7190
Epoch 600/5000 | Batch Loss: 11.8937
Epoch 600/5000 | Batch Loss: 6.3350
Epoch 600/5000 | Batch Loss: 11.9248
Epoch 600/5000 | Batch Loss: 7.2759
Epoch 600/5000 | Batch Loss: 14.5338
Epoch 600/5000 | Batch Loss: 10.9819
Epoch 600/5000 | Batch Loss: 6.9143
Epoch 600/5000 | Batch Loss: 8.8849
Epoch 600/5000 | Batch Loss: 8.3603
Epoch 600/5000 | Batch Loss: 7.0335
Epoch 600/5000 | Batch Loss: 8.0880
Epoch 600/5000 | Batch Loss: 9.0183
Epoch 600/5000 | Batch Loss: 5.4918
Epoch 600/5000 | Batch Loss: 10.6308
Epoch 600/5000 | Batch Loss: 5.7033
Epoch 600/5000 | Batch Loss: 11.7723
Epoch 600/5000 | Batch Loss: 13.6336
Epoch 600/5000 | Batch Loss: 10.0415

Epoch 600: Train Loss: 10.8016 | Val Loss: 29.0512
-----------------------

Epoch 650/5000 | Batch Loss: 5.6476
Epoch 650/5000 | Batch Loss: 10.0195
Epoch 650/5000 | Batch Loss: 13.1334
Epoch 650/5000 | Batch Loss: 12.7711
Epoch 650/5000 | Batch Loss: 11.2262
Epoch 650/5000 | Batch Loss: 8.7477
Epoch 650/5000 | Batch Loss: 8.4910
Epoch 650/5000 | Batch Loss: 11.7235
Epoch 650/5000 | Batch Loss: 14.4383
Epoch 650/5000 | Batch Loss: 9.9154
Epoch 650/5000 | Batch Loss: 11.4722
Epoch 650/5000 | Batch Loss: 10.9192
Epoch 650/5000 | Batch Loss: 10.5941
Epoch 650/5000 | Batch Loss: 14.3588
Epoch 650/5000 | Batch Loss: 23.2053
Epoch 650/5000 | Batch Loss: 8.1029
Epoch 650/5000 | Batch Loss: 12.2742
Epoch 650/5000 | Batch Loss: 4.5602
Epoch 650/5000 | Batch Loss: 8.3975
Epoch 650/5000 | Batch Loss: 13.6084
Epoch 650/5000 | Batch Loss: 4.4549
Epoch 650/5000 | Batch Loss: 9.5488
Epoch 650/5000 | Batch Loss: 11.5086
Epoch 650/5000 | Batch Loss: 8.8383
Epoch 650/5000 | Batch Loss: 10.4201
Epoch 650/5000 | Batch Loss: 5.4606

Epoch 650: Train Loss: 10.5322 | Val Loss: 25.3181
-----------------------

Epoch 700/5000 | Batch Loss: 4.3109
Epoch 700/5000 | Batch Loss: 7.2291
Epoch 700/5000 | Batch Loss: 6.1316
Epoch 700/5000 | Batch Loss: 9.1389
Epoch 700/5000 | Batch Loss: 5.9596
Epoch 700/5000 | Batch Loss: 11.1972
Epoch 700/5000 | Batch Loss: 22.0348
Epoch 700/5000 | Batch Loss: 13.9738
Epoch 700/5000 | Batch Loss: 8.3548
Epoch 700/5000 | Batch Loss: 17.1031
Epoch 700/5000 | Batch Loss: 11.8683
Epoch 700/5000 | Batch Loss: 9.7116
Epoch 700/5000 | Batch Loss: 16.8349
Epoch 700/5000 | Batch Loss: 21.2739
Epoch 700/5000 | Batch Loss: 15.5001
Epoch 700/5000 | Batch Loss: 10.7975
Epoch 700/5000 | Batch Loss: 16.9611
Epoch 700/5000 | Batch Loss: 10.6915
Epoch 700/5000 | Batch Loss: 6.6835
Epoch 700/5000 | Batch Loss: 4.8950
Epoch 700/5000 | Batch Loss: 4.6185
Epoch 700/5000 | Batch Loss: 5.8726
Epoch 700/5000 | Batch Loss: 10.0885
Epoch 700/5000 | Batch Loss: 5.4609
Epoch 700/5000 | Batch Loss: 12.2676
Epoch 700/5000 | Batch Loss: 14.8686

Epoch 700: Train Loss: 10.9165 | Val Loss: 33.2207
-----------------------

Epoch 750/5000 | Batch Loss: 7.5179
Epoch 750/5000 | Batch Loss: 3.9204
Epoch 750/5000 | Batch Loss: 8.3173
Epoch 750/5000 | Batch Loss: 14.5982
Epoch 750/5000 | Batch Loss: 9.3282
Epoch 750/5000 | Batch Loss: 13.6065
Epoch 750/5000 | Batch Loss: 8.9461
Epoch 750/5000 | Batch Loss: 5.4756
Epoch 750/5000 | Batch Loss: 6.3923
Epoch 750/5000 | Batch Loss: 7.1433
Epoch 750/5000 | Batch Loss: 9.2033
Epoch 750/5000 | Batch Loss: 10.3995
Epoch 750/5000 | Batch Loss: 9.3627
Epoch 750/5000 | Batch Loss: 16.6921
Epoch 750/5000 | Batch Loss: 10.3667
Epoch 750/5000 | Batch Loss: 8.8130
Epoch 750/5000 | Batch Loss: 12.3253
Epoch 750/5000 | Batch Loss: 7.2254
Epoch 750/5000 | Batch Loss: 5.0691
Epoch 750/5000 | Batch Loss: 12.3267
Epoch 750/5000 | Batch Loss: 13.9039
Epoch 750/5000 | Batch Loss: 29.3601
Epoch 750/5000 | Batch Loss: 9.2582
Epoch 750/5000 | Batch Loss: 5.5873
Epoch 750/5000 | Batch Loss: 7.2469
Epoch 750/5000 | Batch Loss: 12.2712

Epoch 750: Train Loss: 10.1791 | Val Loss: 27.4870
-----------------------

Epoch 800/5000 | Batch Loss: 6.7258
Epoch 800/5000 | Batch Loss: 4.0455
Epoch 800/5000 | Batch Loss: 13.6837
Epoch 800/5000 | Batch Loss: 9.8983
Epoch 800/5000 | Batch Loss: 6.8079
Epoch 800/5000 | Batch Loss: 10.0442
Epoch 800/5000 | Batch Loss: 14.0362
Epoch 800/5000 | Batch Loss: 7.9482
Epoch 800/5000 | Batch Loss: 4.7155
Epoch 800/5000 | Batch Loss: 25.0657
Epoch 800/5000 | Batch Loss: 9.3971
Epoch 800/5000 | Batch Loss: 7.2613
Epoch 800/5000 | Batch Loss: 3.7483
Epoch 800/5000 | Batch Loss: 5.1872
Epoch 800/5000 | Batch Loss: 7.9364
Epoch 800/5000 | Batch Loss: 7.8749
Epoch 800/5000 | Batch Loss: 18.9620
Epoch 800/5000 | Batch Loss: 8.8211
Epoch 800/5000 | Batch Loss: 7.4067
Epoch 800/5000 | Batch Loss: 8.8219
Epoch 800/5000 | Batch Loss: 7.6416
Epoch 800/5000 | Batch Loss: 10.6872
Epoch 800/5000 | Batch Loss: 10.7951
Epoch 800/5000 | Batch Loss: 11.9718
Epoch 800/5000 | Batch Loss: 6.6034
Epoch 800/5000 | Batch Loss: 8.6000

Epoch 800: Train Loss: 9.4110 | Val Loss: 24.4971
-----------------------

Epoch 850/5000 | Batch Loss: 11.0030
Epoch 850/5000 | Batch Loss: 5.1346
Epoch 850/5000 | Batch Loss: 5.6589
Epoch 850/5000 | Batch Loss: 12.4883
Epoch 850/5000 | Batch Loss: 9.4668
Epoch 850/5000 | Batch Loss: 10.3732
Epoch 850/5000 | Batch Loss: 13.5286
Epoch 850/5000 | Batch Loss: 11.9130
Epoch 850/5000 | Batch Loss: 16.2676
Epoch 850/5000 | Batch Loss: 12.4198
Epoch 850/5000 | Batch Loss: 5.7582
Epoch 850/5000 | Batch Loss: 24.0624
Epoch 850/5000 | Batch Loss: 9.6884
Epoch 850/5000 | Batch Loss: 10.7956
Epoch 850/5000 | Batch Loss: 9.5362
Epoch 850/5000 | Batch Loss: 10.1271
Epoch 850/5000 | Batch Loss: 13.5686
Epoch 850/5000 | Batch Loss: 8.3400
Epoch 850/5000 | Batch Loss: 10.2015
Epoch 850/5000 | Batch Loss: 4.9688
Epoch 850/5000 | Batch Loss: 11.7303
Epoch 850/5000 | Batch Loss: 10.3844
Epoch 850/5000 | Batch Loss: 4.6988
Epoch 850/5000 | Batch Loss: 9.3219
Epoch 850/5000 | Batch Loss: 5.1003
Epoch 850/5000 | Batch Loss: 8.7614

Epoch 850: Train Loss: 10.2038 | Val Loss: 25.2656
-----------------------

Epoch 900/5000 | Batch Loss: 9.0245
Epoch 900/5000 | Batch Loss: 8.3980
Epoch 900/5000 | Batch Loss: 4.3033
Epoch 900/5000 | Batch Loss: 5.8177
Epoch 900/5000 | Batch Loss: 4.9535
Epoch 900/5000 | Batch Loss: 11.1279
Epoch 900/5000 | Batch Loss: 5.5945
Epoch 900/5000 | Batch Loss: 11.7677
Epoch 900/5000 | Batch Loss: 10.0615
Epoch 900/5000 | Batch Loss: 5.0759
Epoch 900/5000 | Batch Loss: 12.1801
Epoch 900/5000 | Batch Loss: 34.5077
Epoch 900/5000 | Batch Loss: 19.9390
Epoch 900/5000 | Batch Loss: 11.5777
Epoch 900/5000 | Batch Loss: 16.4918
Epoch 900/5000 | Batch Loss: 16.3245
Epoch 900/5000 | Batch Loss: 12.9695
Epoch 900/5000 | Batch Loss: 13.6826
Epoch 900/5000 | Batch Loss: 7.0149
Epoch 900/5000 | Batch Loss: 4.4126
Epoch 900/5000 | Batch Loss: 5.2111
Epoch 900/5000 | Batch Loss: 7.4252
Epoch 900/5000 | Batch Loss: 8.8731
Epoch 900/5000 | Batch Loss: 5.3695
Epoch 900/5000 | Batch Loss: 8.9492
Epoch 900/5000 | Batch Loss: 7.6544

Epoch 900: Train Loss: 10.3349 | Val Loss: 28.1707
-----------------------

Epoch 950/5000 | Batch Loss: 7.9624
Epoch 950/5000 | Batch Loss: 11.0916
Epoch 950/5000 | Batch Loss: 12.2248
Epoch 950/5000 | Batch Loss: 8.2540
Epoch 950/5000 | Batch Loss: 5.9201
Epoch 950/5000 | Batch Loss: 6.3402
Epoch 950/5000 | Batch Loss: 4.8827
Epoch 950/5000 | Batch Loss: 5.4713
Epoch 950/5000 | Batch Loss: 7.5406
Epoch 950/5000 | Batch Loss: 14.4323
Epoch 950/5000 | Batch Loss: 11.0332
Epoch 950/5000 | Batch Loss: 6.2902
Epoch 950/5000 | Batch Loss: 28.9023
Epoch 950/5000 | Batch Loss: 15.0553
Epoch 950/5000 | Batch Loss: 18.4272
Epoch 950/5000 | Batch Loss: 16.1671
Epoch 950/5000 | Batch Loss: 8.5285
Epoch 950/5000 | Batch Loss: 6.5100
Epoch 950/5000 | Batch Loss: 5.3692
Epoch 950/5000 | Batch Loss: 11.4253
Epoch 950/5000 | Batch Loss: 12.3688
Epoch 950/5000 | Batch Loss: 12.1883
Epoch 950/5000 | Batch Loss: 9.9108
Epoch 950/5000 | Batch Loss: 6.5179
Epoch 950/5000 | Batch Loss: 6.7116
Epoch 950/5000 | Batch Loss: 11.0342

Epoch 950: Train Loss: 10.4061 | Val Loss: 23.2592
-----------------------

Epoch 1000/5000 | Batch Loss: 5.8809
Epoch 1000/5000 | Batch Loss: 5.4445
Epoch 1000/5000 | Batch Loss: 8.0159
Epoch 1000/5000 | Batch Loss: 22.7914
Epoch 1000/5000 | Batch Loss: 16.9223
Epoch 1000/5000 | Batch Loss: 20.1530
Epoch 1000/5000 | Batch Loss: 7.2550
Epoch 1000/5000 | Batch Loss: 8.5367
Epoch 1000/5000 | Batch Loss: 6.1637
Epoch 1000/5000 | Batch Loss: 9.6091
Epoch 1000/5000 | Batch Loss: 7.5535
Epoch 1000/5000 | Batch Loss: 3.7142

In [7]:
# using Adam AND mini-batch GD
optimizer = optim.Adam(model.parameters(), lr=1e-3)

# training loop
epochs = 5_000

for epoch in range(epochs):

    # --- TRAINING PHASE ---
    model.train() # Set to training mode
    train_loss = 0
    for data, target in train_loader:
        optimizer.zero_grad()
        output = model(data)
        loss = criterion(output, target)
        loss.backward()
        optimizer.step()
        train_loss += loss.item()
        if (epoch + 1) % 50 == 0:
            print(f"Epoch {epoch + 1}/{epochs} | Batch Loss: {loss.item():.4f}")

    # --- VALIDATION PHASE ---
    model.eval() # Set to evaluation mode (turns off Dropout, BatchNorm, etc.)
    val_loss = 0
    with torch.no_grad(): # Disables gradient calculation
        for data, target in val_loader:
            output = model(data)
            loss = criterion(output, target)
            val_loss += loss.item()

    if (epoch + 1) % 50 == 0:
        with torch.no_grad():
            # Calculate average losses
            avg_train = train_loss / len(train_loader)
            avg_val = val_loss / len(val_loader)

            print()
            print(f"Epoch {epoch + 1}: Train Loss: {avg_train:.4f} | Val Loss: {avg_val:.4f}")
            print("-----------------------")
            print()

Epoch 50/5000 | Batch Loss: 7.6546
Epoch 50/5000 | Batch Loss: 3.0914
Epoch 50/5000 | Batch Loss: 1.3433
Epoch 50/5000 | Batch Loss: 2.8224
Epoch 50/5000 | Batch Loss: 6.2043
Epoch 50/5000 | Batch Loss: 2.7023
Epoch 50/5000 | Batch Loss: 2.8067
Epoch 50/5000 | Batch Loss: 2.9531
Epoch 50/5000 | Batch Loss: 2.3890
Epoch 50/5000 | Batch Loss: 3.4240
Epoch 50/5000 | Batch Loss: 1.7195
Epoch 50/5000 | Batch Loss: 2.0214
Epoch 50/5000 | Batch Loss: 5.4651
Epoch 50/5000 | Batch Loss: 2.1088
Epoch 50/5000 | Batch Loss: 3.1828
Epoch 50/5000 | Batch Loss: 2.4131
Epoch 50/5000 | Batch Loss: 3.1177
Epoch 50/5000 | Batch Loss: 5.8241
Epoch 50/5000 | Batch Loss: 2.5194
Epoch 50/5000 | Batch Loss: 4.3087
Epoch 50/5000 | Batch Loss: 3.6515
Epoch 50/5000 | Batch Loss: 3.8007
Epoch 50/5000 | Batch Loss: 2.0458
Epoch 50/5000 | Batch Loss: 1.8122
Epoch 50/5000 | Batch Loss: 19.9126
Epoch 50/5000 | Batch Loss: 2.1361

Epoch 50: Train Loss: 3.9012 | Val Loss: 21.5144
-----------------------

Epoch 100/5000 | Batch Loss: 3.7802
Epoch 100/5000 | Batch Loss: 2.3813
Epoch 100/5000 | Batch Loss: 2.6697
Epoch 100/5000 | Batch Loss: 1.7360
Epoch 100/5000 | Batch Loss: 3.7502
Epoch 100/5000 | Batch Loss: 1.2999
Epoch 100/5000 | Batch Loss: 4.5464
Epoch 100/5000 | Batch Loss: 3.9402
Epoch 100/5000 | Batch Loss: 2.0199
Epoch 100/5000 | Batch Loss: 18.7399
Epoch 100/5000 | Batch Loss: 1.8689
Epoch 100/5000 | Batch Loss: 1.7884
Epoch 100/5000 | Batch Loss: 5.8948
Epoch 100/5000 | Batch Loss: 3.1689
Epoch 100/5000 | Batch Loss: 2.3642
Epoch 100/5000 | Batch Loss: 3.4690
Epoch 100/5000 | Batch Loss: 2.5869
Epoch 100/5000 | Batch Loss: 1.4624
Epoch 100/5000 | Batch Loss: 1.9865
Epoch 100/5000 | Batch Loss: 4.1356
Epoch 100/5000 | Batch Loss: 3.5132
Epoch 100/5000 | Batch Loss: 4.1448
Epoch 100/5000 | Batch Loss: 5.0405
Epoch 100/5000 | Batch Loss: 5.2751
Epoch 100/5000 | Batch Loss: 3.1551
Epoch 100/5000 | Batch Loss: 6.5950

Epoch 100: Train Loss: 3.8967 | Val Loss: 20.6405
-----------------------

Epoch 150/5000 | Batch Loss: 2.2657
Epoch 150/5000 | Batch Loss: 4.2527
Epoch 150/5000 | Batch Loss: 3.3803
Epoch 150/5000 | Batch Loss: 2.3533
Epoch 150/5000 | Batch Loss: 3.0821
Epoch 150/5000 | Batch Loss: 3.2818
Epoch 150/5000 | Batch Loss: 2.9319
Epoch 150/5000 | Batch Loss: 4.3929
Epoch 150/5000 | Batch Loss: 0.6594
Epoch 150/5000 | Batch Loss: 5.6616
Epoch 150/5000 | Batch Loss: 1.6837
Epoch 150/5000 | Batch Loss: 2.9321
Epoch 150/5000 | Batch Loss: 1.8406
Epoch 150/5000 | Batch Loss: 2.3827
Epoch 150/5000 | Batch Loss: 1.6514
Epoch 150/5000 | Batch Loss: 3.8958
Epoch 150/5000 | Batch Loss: 4.8328
Epoch 150/5000 | Batch Loss: 4.0899
Epoch 150/5000 | Batch Loss: 4.2738
Epoch 150/5000 | Batch Loss: 2.6486
Epoch 150/5000 | Batch Loss: 2.0559
Epoch 150/5000 | Batch Loss: 2.7298
Epoch 150/5000 | Batch Loss: 22.6387
Epoch 150/5000 | Batch Loss: 3.7996
Epoch 150/5000 | Batch Loss: 2.5215
Epoch 150/5000 | Batch Loss: 2.3156

Epoch 150: Train Loss: 3.7906 | Val Loss: 20.9960
-----------------------

Epoch 200/5000 | Batch Loss: 1.6702
Epoch 200/5000 | Batch Loss: 1.8087
Epoch 200/5000 | Batch Loss: 3.2829
Epoch 200/5000 | Batch Loss: 2.2592
Epoch 200/5000 | Batch Loss: 2.1084
Epoch 200/5000 | Batch Loss: 3.4077
Epoch 200/5000 | Batch Loss: 3.5163
Epoch 200/5000 | Batch Loss: 19.8332
Epoch 200/5000 | Batch Loss: 4.1858
Epoch 200/5000 | Batch Loss: 4.3381
Epoch 200/5000 | Batch Loss: 1.5983
Epoch 200/5000 | Batch Loss: 3.7244
Epoch 200/5000 | Batch Loss: 7.7763
Epoch 200/5000 | Batch Loss: 2.2470
Epoch 200/5000 | Batch Loss: 1.8383
Epoch 200/5000 | Batch Loss: 2.7372
Epoch 200/5000 | Batch Loss: 4.8460
Epoch 200/5000 | Batch Loss: 2.5109
Epoch 200/5000 | Batch Loss: 2.3371
Epoch 200/5000 | Batch Loss: 4.2215
Epoch 200/5000 | Batch Loss: 5.0389
Epoch 200/5000 | Batch Loss: 2.2559
Epoch 200/5000 | Batch Loss: 3.6221
Epoch 200/5000 | Batch Loss: 2.9084
Epoch 200/5000 | Batch Loss: 2.2636
Epoch 200/5000 | Batch Loss: 3.6895

Epoch 200: Train Loss: 3.8471 | Val Loss: 20.1240
-----------------------

Epoch 250/5000 | Batch Loss: 1.2338
Epoch 250/5000 | Batch Loss: 1.6989
Epoch 250/5000 | Batch Loss: 2.8041
Epoch 250/5000 | Batch Loss: 1.8416
Epoch 250/5000 | Batch Loss: 2.6471
Epoch 250/5000 | Batch Loss: 2.3117
Epoch 250/5000 | Batch Loss: 3.4010
Epoch 250/5000 | Batch Loss: 3.3206
Epoch 250/5000 | Batch Loss: 1.8298
Epoch 250/5000 | Batch Loss: 4.7567
Epoch 250/5000 | Batch Loss: 2.2509
Epoch 250/5000 | Batch Loss: 4.8555
Epoch 250/5000 | Batch Loss: 4.1589
Epoch 250/5000 | Batch Loss: 5.2221
Epoch 250/5000 | Batch Loss: 4.0187
Epoch 250/5000 | Batch Loss: 3.5226
Epoch 250/5000 | Batch Loss: 1.1960
Epoch 250/5000 | Batch Loss: 2.2207
Epoch 250/5000 | Batch Loss: 2.9370
Epoch 250/5000 | Batch Loss: 2.3409
Epoch 250/5000 | Batch Loss: 24.2317
Epoch 250/5000 | Batch Loss: 2.6976
Epoch 250/5000 | Batch Loss: 4.5903
Epoch 250/5000 | Batch Loss: 4.2064
Epoch 250/5000 | Batch Loss: 2.3261
Epoch 250/5000 | Batch Loss: 2.1424

Epoch 250: Train Loss: 3.7986 | Val Loss: 20.5488
-----------------------

Epoch 300/5000 | Batch Loss: 2.7065
Epoch 300/5000 | Batch Loss: 5.0581
Epoch 300/5000 | Batch Loss: 2.7881
Epoch 300/5000 | Batch Loss: 1.8784
Epoch 300/5000 | Batch Loss: 3.3055
Epoch 300/5000 | Batch Loss: 3.6485
Epoch 300/5000 | Batch Loss: 3.6963
Epoch 300/5000 | Batch Loss: 3.6506
Epoch 300/5000 | Batch Loss: 2.5300
Epoch 300/5000 | Batch Loss: 2.1759
Epoch 300/5000 | Batch Loss: 3.9350
Epoch 300/5000 | Batch Loss: 19.5977
Epoch 300/5000 | Batch Loss: 1.1906
Epoch 300/5000 | Batch Loss: 5.8716
Epoch 300/5000 | Batch Loss: 4.2452
Epoch 300/5000 | Batch Loss: 2.6752
Epoch 300/5000 | Batch Loss: 3.2349
Epoch 300/5000 | Batch Loss: 5.2191
Epoch 300/5000 | Batch Loss: 3.2244
Epoch 300/5000 | Batch Loss: 3.1318
Epoch 300/5000 | Batch Loss: 4.8020
Epoch 300/5000 | Batch Loss: 2.4345
Epoch 300/5000 | Batch Loss: 2.0663
Epoch 300/5000 | Batch Loss: 1.6957
Epoch 300/5000 | Batch Loss: 3.1297
Epoch 300/5000 | Batch Loss: 3.2765

Epoch 300: Train Loss: 3.8911 | Val Loss: 20.5691
-----------------------

Epoch 350/5000 | Batch Loss: 3.6482
Epoch 350/5000 | Batch Loss: 3.9037
Epoch 350/5000 | Batch Loss: 2.5023
Epoch 350/5000 | Batch Loss: 1.8620
Epoch 350/5000 | Batch Loss: 2.8981
Epoch 350/5000 | Batch Loss: 2.4338
Epoch 350/5000 | Batch Loss: 7.4821
Epoch 350/5000 | Batch Loss: 2.1965
Epoch 350/5000 | Batch Loss: 2.1147
Epoch 350/5000 | Batch Loss: 1.6782
Epoch 350/5000 | Batch Loss: 3.4741
Epoch 350/5000 | Batch Loss: 3.0558
Epoch 350/5000 | Batch Loss: 2.8084
Epoch 350/5000 | Batch Loss: 3.0370
Epoch 350/5000 | Batch Loss: 2.1028
Epoch 350/5000 | Batch Loss: 4.5419
Epoch 350/5000 | Batch Loss: 3.1459
Epoch 350/5000 | Batch Loss: 6.0464
Epoch 350/5000 | Batch Loss: 1.4847
Epoch 350/5000 | Batch Loss: 5.5806
Epoch 350/5000 | Batch Loss: 3.4965
Epoch 350/5000 | Batch Loss: 4.2924
Epoch 350/5000 | Batch Loss: 1.9166
Epoch 350/5000 | Batch Loss: 3.4768
Epoch 350/5000 | Batch Loss: 21.1268
Epoch 350/5000 | Batch Loss: 3.0450

Epoch 350: Train Loss: 3.9750 | Val Loss: 20.5181
-----------------------

Epoch 400/5000 | Batch Loss: 3.6509
Epoch 400/5000 | Batch Loss: 2.0927
Epoch 400/5000 | Batch Loss: 1.6269
Epoch 400/5000 | Batch Loss: 3.6219
Epoch 400/5000 | Batch Loss: 2.0991
Epoch 400/5000 | Batch Loss: 2.5633
Epoch 400/5000 | Batch Loss: 3.0330
Epoch 400/5000 | Batch Loss: 19.1237
Epoch 400/5000 | Batch Loss: 2.1328
Epoch 400/5000 | Batch Loss: 1.9443
Epoch 400/5000 | Batch Loss: 3.3807
Epoch 400/5000 | Batch Loss: 2.1399
Epoch 400/5000 | Batch Loss: 3.6244
Epoch 400/5000 | Batch Loss: 6.3245
Epoch 400/5000 | Batch Loss: 2.9617
Epoch 400/5000 | Batch Loss: 4.3046
Epoch 400/5000 | Batch Loss: 3.5770
Epoch 400/5000 | Batch Loss: 2.1585
Epoch 400/5000 | Batch Loss: 5.9781
Epoch 400/5000 | Batch Loss: 3.1210
Epoch 400/5000 | Batch Loss: 3.7828
Epoch 400/5000 | Batch Loss: 5.7600
Epoch 400/5000 | Batch Loss: 3.8443
Epoch 400/5000 | Batch Loss: 3.0136
Epoch 400/5000 | Batch Loss: 2.1111
Epoch 400/5000 | Batch Loss: 2.5330

Epoch 400: Train Loss: 3.8655 | Val Loss: 20.9287
-----------------------

Epoch 450/5000 | Batch Loss: 2.4067
Epoch 450/5000 | Batch Loss: 2.5418
Epoch 450/5000 | Batch Loss: 1.3621
Epoch 450/5000 | Batch Loss: 2.0173
Epoch 450/5000 | Batch Loss: 3.2295
Epoch 450/5000 | Batch Loss: 19.5391
Epoch 450/5000 | Batch Loss: 5.7345
Epoch 450/5000 | Batch Loss: 3.1526
Epoch 450/5000 | Batch Loss: 2.6964
Epoch 450/5000 | Batch Loss: 3.0376
Epoch 450/5000 | Batch Loss: 2.3731
Epoch 450/5000 | Batch Loss: 4.0755
Epoch 450/5000 | Batch Loss: 2.8551
Epoch 450/5000 | Batch Loss: 2.2953
Epoch 450/5000 | Batch Loss: 2.3770
Epoch 450/5000 | Batch Loss: 3.4209
Epoch 450/5000 | Batch Loss: 4.0048
Epoch 450/5000 | Batch Loss: 8.0669
Epoch 450/5000 | Batch Loss: 3.7062
Epoch 450/5000 | Batch Loss: 2.4546
Epoch 450/5000 | Batch Loss: 2.8048
Epoch 450/5000 | Batch Loss: 2.1357
Epoch 450/5000 | Batch Loss: 2.9792
Epoch 450/5000 | Batch Loss: 1.6540
Epoch 450/5000 | Batch Loss: 4.6362
Epoch 450/5000 | Batch Loss: 5.7912

Epoch 450: Train Loss: 3.8980 | Val Loss: 20.5510
-----------------------

Epoch 500/5000 | Batch Loss: 2.9678
Epoch 500/5000 | Batch Loss: 3.2796
Epoch 500/5000 | Batch Loss: 2.2988
Epoch 500/5000 | Batch Loss: 1.5004
Epoch 500/5000 | Batch Loss: 1.9264
Epoch 500/5000 | Batch Loss: 1.9600
Epoch 500/5000 | Batch Loss: 1.1564
Epoch 500/5000 | Batch Loss: 3.1486
Epoch 500/5000 | Batch Loss: 1.8990
Epoch 500/5000 | Batch Loss: 3.0780
Epoch 500/5000 | Batch Loss: 1.8148
Epoch 500/5000 | Batch Loss: 2.7908
Epoch 500/5000 | Batch Loss: 4.9251
Epoch 500/5000 | Batch Loss: 21.0395
Epoch 500/5000 | Batch Loss: 3.1473
Epoch 500/5000 | Batch Loss: 2.5972
Epoch 500/5000 | Batch Loss: 3.1249
Epoch 500/5000 | Batch Loss: 3.8302
Epoch 500/5000 | Batch Loss: 1.8953
Epoch 500/5000 | Batch Loss: 3.3711
Epoch 500/5000 | Batch Loss: 6.3253
Epoch 500/5000 | Batch Loss: 2.5686
Epoch 500/5000 | Batch Loss: 4.8004
Epoch 500/5000 | Batch Loss: 3.2576
Epoch 500/5000 | Batch Loss: 5.1718
Epoch 500/5000 | Batch Loss: 1.6183

Epoch 500: Train Loss: 3.6728 | Val Loss: 20.1759
-----------------------

Epoch 550/5000 | Batch Loss: 3.8466
Epoch 550/5000 | Batch Loss: 2.2629
Epoch 550/5000 | Batch Loss: 1.7539
Epoch 550/5000 | Batch Loss: 4.2109
Epoch 550/5000 | Batch Loss: 5.5312
Epoch 550/5000 | Batch Loss: 2.0051
Epoch 550/5000 | Batch Loss: 1.8864
Epoch 550/5000 | Batch Loss: 1.3091
Epoch 550/5000 | Batch Loss: 4.1538
Epoch 550/5000 | Batch Loss: 2.7146
Epoch 550/5000 | Batch Loss: 4.4869
Epoch 550/5000 | Batch Loss: 2.0930
Epoch 550/5000 | Batch Loss: 20.3713
Epoch 550/5000 | Batch Loss: 3.4850
Epoch 550/5000 | Batch Loss: 5.1270
Epoch 550/5000 | Batch Loss: 3.9930
Epoch 550/5000 | Batch Loss: 4.7118
Epoch 550/5000 | Batch Loss: 1.8397
Epoch 550/5000 | Batch Loss: 1.4277
Epoch 550/5000 | Batch Loss: 1.7131
Epoch 550/5000 | Batch Loss: 1.5346
Epoch 550/5000 | Batch Loss: 3.4628
Epoch 550/5000 | Batch Loss: 4.6274
Epoch 550/5000 | Batch Loss: 2.9976
Epoch 550/5000 | Batch Loss: 1.5478
Epoch 550/5000 | Batch Loss: 3.7143

Epoch 550: Train Loss: 3.7234 | Val Loss: 20.3421
-----------------------

Epoch 600/5000 | Batch Loss: 2.1560
Epoch 600/5000 | Batch Loss: 6.4267
Epoch 600/5000 | Batch Loss: 5.8466
Epoch 600/5000 | Batch Loss: 4.2042
Epoch 600/5000 | Batch Loss: 2.8656
Epoch 600/5000 | Batch Loss: 22.2146
Epoch 600/5000 | Batch Loss: 1.5606
Epoch 600/5000 | Batch Loss: 3.2674
Epoch 600/5000 | Batch Loss: 2.3517
Epoch 600/5000 | Batch Loss: 3.9737
Epoch 600/5000 | Batch Loss: 2.0144
Epoch 600/5000 | Batch Loss: 3.6775
Epoch 600/5000 | Batch Loss: 1.6718
Epoch 600/5000 | Batch Loss: 3.5832
Epoch 600/5000 | Batch Loss: 2.4530
Epoch 600/5000 | Batch Loss: 2.9322
Epoch 600/5000 | Batch Loss: 4.5609
Epoch 600/5000 | Batch Loss: 2.2697
Epoch 600/5000 | Batch Loss: 2.5466
Epoch 600/5000 | Batch Loss: 2.7182
Epoch 600/5000 | Batch Loss: 3.3241
Epoch 600/5000 | Batch Loss: 1.3567
Epoch 600/5000 | Batch Loss: 1.6721
Epoch 600/5000 | Batch Loss: 2.1461
Epoch 600/5000 | Batch Loss: 1.6272
Epoch 600/5000 | Batch Loss: 1.5669

Epoch 600: Train Loss: 3.6534 | Val Loss: 20.6236
-----------------------

Epoch 650/5000 | Batch Loss: 2.6963
Epoch 650/5000 | Batch Loss: 5.3588
Epoch 650/5000 | Batch Loss: 3.3072
Epoch 650/5000 | Batch Loss: 2.3860
Epoch 650/5000 | Batch Loss: 1.9086
Epoch 650/5000 | Batch Loss: 6.0694
Epoch 650/5000 | Batch Loss: 2.1921
Epoch 650/5000 | Batch Loss: 1.9286
Epoch 650/5000 | Batch Loss: 2.0563
Epoch 650/5000 | Batch Loss: 1.5154
Epoch 650/5000 | Batch Loss: 3.9061
Epoch 650/5000 | Batch Loss: 7.8598
Epoch 650/5000 | Batch Loss: 2.0201
Epoch 650/5000 | Batch Loss: 3.5725
Epoch 650/5000 | Batch Loss: 2.8560
Epoch 650/5000 | Batch Loss: 2.5914
Epoch 650/5000 | Batch Loss: 2.4034
Epoch 650/5000 | Batch Loss: 1.7390
Epoch 650/5000 | Batch Loss: 2.4534
Epoch 650/5000 | Batch Loss: 1.9776
Epoch 650/5000 | Batch Loss: 20.2787
Epoch 650/5000 | Batch Loss: 3.4088
Epoch 650/5000 | Batch Loss: 4.1842
Epoch 650/5000 | Batch Loss: 4.5883
Epoch 650/5000 | Batch Loss: 1.8242
Epoch 650/5000 | Batch Loss: 1.8422

Epoch 650: Train Loss: 3.7279 | Val Loss: 21.1933
-----------------------

Epoch 700/5000 | Batch Loss: 3.9348
Epoch 700/5000 | Batch Loss: 4.1371
Epoch 700/5000 | Batch Loss: 1.1992
Epoch 700/5000 | Batch Loss: 6.0727
Epoch 700/5000 | Batch Loss: 1.8318
Epoch 700/5000 | Batch Loss: 5.1670
Epoch 700/5000 | Batch Loss: 3.0734
Epoch 700/5000 | Batch Loss: 2.0830
Epoch 700/5000 | Batch Loss: 3.7109
Epoch 700/5000 | Batch Loss: 2.4660
Epoch 700/5000 | Batch Loss: 1.8752
Epoch 700/5000 | Batch Loss: 3.9488
Epoch 700/5000 | Batch Loss: 1.9423
Epoch 700/5000 | Batch Loss: 1.9853
Epoch 700/5000 | Batch Loss: 3.3042
Epoch 700/5000 | Batch Loss: 6.7894
Epoch 700/5000 | Batch Loss: 1.1900
Epoch 700/5000 | Batch Loss: 2.6614
Epoch 700/5000 | Batch Loss: 0.9155
Epoch 700/5000 | Batch Loss: 21.7388
Epoch 700/5000 | Batch Loss: 3.1764
Epoch 700/5000 | Batch Loss: 2.4138
Epoch 700/5000 | Batch Loss: 4.8000
Epoch 700/5000 | Batch Loss: 2.3847
Epoch 700/5000 | Batch Loss: 2.0759
Epoch 700/5000 | Batch Loss: 2.7009

Epoch 700: Train Loss: 3.7530 | Val Loss: 21.6108
-----------------------

Epoch 750/5000 | Batch Loss: 2.5551
Epoch 750/5000 | Batch Loss: 1.5256
Epoch 750/5000 | Batch Loss: 1.7192
Epoch 750/5000 | Batch Loss: 5.0174
Epoch 750/5000 | Batch Loss: 2.8470
Epoch 750/5000 | Batch Loss: 1.8528
Epoch 750/5000 | Batch Loss: 3.5964
Epoch 750/5000 | Batch Loss: 5.0995
Epoch 750/5000 | Batch Loss: 1.5655
Epoch 750/5000 | Batch Loss: 2.8933
Epoch 750/5000 | Batch Loss: 2.9685
Epoch 750/5000 | Batch Loss: 1.8296
Epoch 750/5000 | Batch Loss: 2.3347
Epoch 750/5000 | Batch Loss: 1.1713
Epoch 750/5000 | Batch Loss: 2.7152
Epoch 750/5000 | Batch Loss: 1.7869
Epoch 750/5000 | Batch Loss: 22.0400
Epoch 750/5000 | Batch Loss: 3.2251
Epoch 750/5000 | Batch Loss: 3.5206
Epoch 750/5000 | Batch Loss: 3.8471
Epoch 750/5000 | Batch Loss: 4.2484
Epoch 750/5000 | Batch Loss: 3.8414
Epoch 750/5000 | Batch Loss: 2.8613
Epoch 750/5000 | Batch Loss: 2.1470
Epoch 750/5000 | Batch Loss: 5.1534
Epoch 750/5000 | Batch Loss: 1.7605

Epoch 750: Train Loss: 3.6201 | Val Loss: 20.5619
-----------------------

Epoch 800/5000 | Batch Loss: 1.5441
Epoch 800/5000 | Batch Loss: 0.9836
Epoch 800/5000 | Batch Loss: 18.9442
Epoch 800/5000 | Batch Loss: 2.3879
Epoch 800/5000 | Batch Loss: 3.8014
Epoch 800/5000 | Batch Loss: 1.2176
Epoch 800/5000 | Batch Loss: 4.7975
Epoch 800/5000 | Batch Loss: 4.9045
Epoch 800/5000 | Batch Loss: 3.0009
Epoch 800/5000 | Batch Loss: 1.3343
Epoch 800/5000 | Batch Loss: 4.0235
Epoch 800/5000 | Batch Loss: 2.2012
Epoch 800/5000 | Batch Loss: 3.8090
Epoch 800/5000 | Batch Loss: 1.1418
Epoch 800/5000 | Batch Loss: 2.7730
Epoch 800/5000 | Batch Loss: 4.3762
Epoch 800/5000 | Batch Loss: 1.6707
Epoch 800/5000 | Batch Loss: 2.7784
Epoch 800/5000 | Batch Loss: 2.9850
Epoch 800/5000 | Batch Loss: 1.5329
Epoch 800/5000 | Batch Loss: 8.0378
Epoch 800/5000 | Batch Loss: 4.0424
Epoch 800/5000 | Batch Loss: 1.8147
Epoch 800/5000 | Batch Loss: 2.0862
Epoch 800/5000 | Batch Loss: 5.2677
Epoch 800/5000 | Batch Loss: 1.1797

Epoch 800: Train Loss: 3.5629 | Val Loss: 21.6025
-----------------------

Epoch 850/5000 | Batch Loss: 3.9912
Epoch 850/5000 | Batch Loss: 3.0312
Epoch 850/5000 | Batch Loss: 3.2179
Epoch 850/5000 | Batch Loss: 2.1929
Epoch 850/5000 | Batch Loss: 1.7675
Epoch 850/5000 | Batch Loss: 3.6869
Epoch 850/5000 | Batch Loss: 1.6349
Epoch 850/5000 | Batch Loss: 3.2095
Epoch 850/5000 | Batch Loss: 2.0095
Epoch 850/5000 | Batch Loss: 20.3470
Epoch 850/5000 | Batch Loss: 2.0550
Epoch 850/5000 | Batch Loss: 2.1826
Epoch 850/5000 | Batch Loss: 1.7678
Epoch 850/5000 | Batch Loss: 4.7653
Epoch 850/5000 | Batch Loss: 2.3893
Epoch 850/5000 | Batch Loss: 3.2886
Epoch 850/5000 | Batch Loss: 2.8200
Epoch 850/5000 | Batch Loss: 2.0571
Epoch 850/5000 | Batch Loss: 3.3437
Epoch 850/5000 | Batch Loss: 2.5969
Epoch 850/5000 | Batch Loss: 3.8182
Epoch 850/5000 | Batch Loss: 1.8897
Epoch 850/5000 | Batch Loss: 5.9525
Epoch 850/5000 | Batch Loss: 3.0156
Epoch 850/5000 | Batch Loss: 4.0694
Epoch 850/5000 | Batch Loss: 2.5449

Epoch 850: Train Loss: 3.6017 | Val Loss: 20.0761
-----------------------

Epoch 900/5000 | Batch Loss: 2.0736
Epoch 900/5000 | Batch Loss: 2.9846
Epoch 900/5000 | Batch Loss: 19.5296
Epoch 900/5000 | Batch Loss: 2.8949
Epoch 900/5000 | Batch Loss: 2.2232
Epoch 900/5000 | Batch Loss: 1.4696
Epoch 900/5000 | Batch Loss: 2.3174
Epoch 900/5000 | Batch Loss: 0.8980
Epoch 900/5000 | Batch Loss: 2.3455
Epoch 900/5000 | Batch Loss: 2.3901
Epoch 900/5000 | Batch Loss: 2.7384
Epoch 900/5000 | Batch Loss: 2.6035
Epoch 900/5000 | Batch Loss: 6.8579
Epoch 900/5000 | Batch Loss: 5.1472
Epoch 900/5000 | Batch Loss: 2.1506
Epoch 900/5000 | Batch Loss: 4.8925
Epoch 900/5000 | Batch Loss: 1.9612
Epoch 900/5000 | Batch Loss: 1.5021
Epoch 900/5000 | Batch Loss: 2.6391
Epoch 900/5000 | Batch Loss: 3.8329
Epoch 900/5000 | Batch Loss: 2.4560
Epoch 900/5000 | Batch Loss: 2.1782
Epoch 900/5000 | Batch Loss: 4.8336
Epoch 900/5000 | Batch Loss: 3.3262
Epoch 900/5000 | Batch Loss: 3.0178
Epoch 900/5000 | Batch Loss: 2.9819

Epoch 900: Train Loss: 3.5479 | Val Loss: 20.6037
-----------------------

Epoch 950/5000 | Batch Loss: 1.9070
Epoch 950/5000 | Batch Loss: 1.1330
Epoch 950/5000 | Batch Loss: 3.0611
Epoch 950/5000 | Batch Loss: 2.0854
Epoch 950/5000 | Batch Loss: 4.3620
Epoch 950/5000 | Batch Loss: 1.1594
Epoch 950/5000 | Batch Loss: 4.6493
Epoch 950/5000 | Batch Loss: 20.3589
Epoch 950/5000 | Batch Loss: 2.1161
Epoch 950/5000 | Batch Loss: 1.4182
Epoch 950/5000 | Batch Loss: 4.1632
Epoch 950/5000 | Batch Loss: 4.0073
Epoch 950/5000 | Batch Loss: 2.6329
Epoch 950/5000 | Batch Loss: 4.4612
Epoch 950/5000 | Batch Loss: 2.5400
Epoch 950/5000 | Batch Loss: 2.6285
Epoch 950/5000 | Batch Loss: 2.3434
Epoch 950/5000 | Batch Loss: 2.3185
Epoch 950/5000 | Batch Loss: 3.4545
Epoch 950/5000 | Batch Loss: 3.4116
Epoch 950/5000 | Batch Loss: 2.8565
Epoch 950/5000 | Batch Loss: 2.0379
Epoch 950/5000 | Batch Loss: 2.4748
Epoch 950/5000 | Batch Loss: 6.2481
Epoch 950/5000 | Batch Loss: 2.0520
Epoch 950/5000 | Batch Loss: 1.5508

Epoch 950: Train Loss: 3.5166 | Val Loss: 21.7224
-----------------------

Epoch 1000/5000 | Batch Loss: 2.7640
Epoch 1000/5000 | Batch Loss: 1.7863
Epoch 1000/5000 | Batch Loss: 3.5173
Epoch 1000/5000 | Batch Loss: 4.1310
Epoch 1000/5000 | Batch Loss: 2.8182
Epoch 1000/5000 | Batch Loss: 2.6812
Epoch 1000/5000 | Batch Loss: 2.6064
Epoch 1000/5000 | Batch Loss: 1.9110
Epoch 1000/5000 | Batch Loss: 5.8950
Epoch 1000/5000 | Batch Loss: 4.3256
Epoch 1000/5000 | Batch Loss: 1.6076
Epoch 1000/5000 | Batch Loss: 1.5239
Epoch 1000/5000 | Batch Loss: 2.2302
Epoch 1000/5000 | Batch Loss: 1.5156
Epoch 1000/5000 | Batch Loss: 5.3700
Epoch 1000/5000 | Batch Loss: 21.4934
Epoch 1000/5000 | Batch Loss: 1.8831
Epoch 1000/5000 | Batch Loss: 4.6952
Epoch 1000/5000 | Batch Loss: 5.4551
Epoch 1000/5000 | Batch Loss: 1.9301
Epoch 1000/5000 | Batch Loss: 1.9755

In [8]:
# using a learning rate decay with Adam and mini-batch GD
optimizer = optim.Adam(model.parameters(), lr=1e-3)

# LR Decay
# This will multiply the LR by 0.1 every 20 epochs
scheduler = StepLR(optimizer, step_size=20, gamma=0.1)

# training loop
epochs = 5_000

for epoch in range(epochs):

    # --- TRAINING PHASE ---
    model.train() # Set to training mode
    train_loss = 0
    for data, target in train_loader:
        optimizer.zero_grad()
        output = model(data)
        loss = criterion(output, target)
        loss.backward()
        optimizer.step()
        train_loss += loss.item()
        if (epoch + 1) % 50 == 0:
            print(f"Epoch {epoch + 1}/{epochs} | Batch Loss: {loss.item():.4f}")

    # --- VALIDATION PHASE ---
    model.eval() # Set to evaluation mode (turns off Dropout, BatchNorm, etc.)
    val_loss = 0
    with torch.no_grad(): # Disables gradient calculation
        for data, target in val_loader:
            output = model(data)
            loss = criterion(output, target)
            val_loss += loss.item()

    if (epoch + 1) % 50 == 0:
        with torch.no_grad():
            # Calculate average losses
            avg_train = train_loss / len(train_loader)
            avg_val = val_loss / len(val_loader)

            print()
            print(f"Epoch {epoch + 1}: Train Loss: {avg_train:.4f} | Val Loss: {avg_val:.4f}")
            print("-----------------------")
            print()

Epoch 50/5000 | Batch Loss: 1.6771
Epoch 50/5000 | Batch Loss: 2.6873
Epoch 50/5000 | Batch Loss: 1.8181
Epoch 50/5000 | Batch Loss: 4.8303
Epoch 50/5000 | Batch Loss: 1.9698
Epoch 50/5000 | Batch Loss: 1.6503
Epoch 50/5000 | Batch Loss: 3.3663
Epoch 50/5000 | Batch Loss: 3.9272
Epoch 50/5000 | Batch Loss: 1.1223
Epoch 50/5000 | Batch Loss: 19.9873
Epoch 50/5000 | Batch Loss: 2.2164
Epoch 50/5000 | Batch Loss: 0.9000
Epoch 50/5000 | Batch Loss: 3.6910
Epoch 50/5000 | Batch Loss: 3.0001
Epoch 50/5000 | Batch Loss: 0.4815
Epoch 50/5000 | Batch Loss: 1.5439
Epoch 50/5000 | Batch Loss: 1.5981
Epoch 50/5000 | Batch Loss: 1.5676
Epoch 50/5000 | Batch Loss: 1.6602
Epoch 50/5000 | Batch Loss: 1.7491
Epoch 50/5000 | Batch Loss: 1.2619
Epoch 50/5000 | Batch Loss: 1.0557
Epoch 50/5000 | Batch Loss: 1.4159
Epoch 50/5000 | Batch Loss: 4.8364
Epoch 50/5000 | Batch Loss: 1.8251
Epoch 50/5000 | Batch Loss: 0.8320

Epoch 50: Train Loss: 2.7950 | Val Loss: 25.0042
-----------------------

Epoch 100/5000 | Batch Loss: 3.2110
Epoch 100/5000 | Batch Loss: 1.2869
Epoch 100/5000 | Batch Loss: 2.5254
Epoch 100/5000 | Batch Loss: 2.2499
Epoch 100/5000 | Batch Loss: 1.5998
Epoch 100/5000 | Batch Loss: 18.1106
Epoch 100/5000 | Batch Loss: 1.6119
Epoch 100/5000 | Batch Loss: 0.9186
Epoch 100/5000 | Batch Loss: 3.5342
Epoch 100/5000 | Batch Loss: 1.1728
Epoch 100/5000 | Batch Loss: 1.4727
Epoch 100/5000 | Batch Loss: 1.7393
Epoch 100/5000 | Batch Loss: 5.6792
Epoch 100/5000 | Batch Loss: 1.9558
Epoch 100/5000 | Batch Loss: 1.3591
Epoch 100/5000 | Batch Loss: 1.0826
Epoch 100/5000 | Batch Loss: 1.4109
Epoch 100/5000 | Batch Loss: 3.2622
Epoch 100/5000 | Batch Loss: 3.8650
Epoch 100/5000 | Batch Loss: 2.7691
Epoch 100/5000 | Batch Loss: 4.1290
Epoch 100/5000 | Batch Loss: 1.7137
Epoch 100/5000 | Batch Loss: 3.9445
Epoch 100/5000 | Batch Loss: 1.2670
Epoch 100/5000 | Batch Loss: 1.2502
Epoch 100/5000 | Batch Loss: 2.6509

Epoch 100: Train Loss: 2.9143 | Val Loss: 24.7591
-----------------------

Epoch 150/5000 | Batch Loss: 0.8099
Epoch 150/5000 | Batch Loss: 1.2489
Epoch 150/5000 | Batch Loss: 4.8762
Epoch 150/5000 | Batch Loss: 1.8288
Epoch 150/5000 | Batch Loss: 3.1569
Epoch 150/5000 | Batch Loss: 1.3388
Epoch 150/5000 | Batch Loss: 2.5807
Epoch 150/5000 | Batch Loss: 2.8812
Epoch 150/5000 | Batch Loss: 2.2606
Epoch 150/5000 | Batch Loss: 2.4658
Epoch 150/5000 | Batch Loss: 18.6879
Epoch 150/5000 | Batch Loss: 2.1551
Epoch 150/5000 | Batch Loss: 1.5730
Epoch 150/5000 | Batch Loss: 0.8477
Epoch 150/5000 | Batch Loss: 1.6147
Epoch 150/5000 | Batch Loss: 2.8282
Epoch 150/5000 | Batch Loss: 1.2754
Epoch 150/5000 | Batch Loss: 0.7001
Epoch 150/5000 | Batch Loss: 1.5911
Epoch 150/5000 | Batch Loss: 9.3530
Epoch 150/5000 | Batch Loss: 1.2388
Epoch 150/5000 | Batch Loss: 1.2932
Epoch 150/5000 | Batch Loss: 1.3026
Epoch 150/5000 | Batch Loss: 3.0841
Epoch 150/5000 | Batch Loss: 1.3583
Epoch 150/5000 | Batch Loss: 1.8910

Epoch 150: Train Loss: 2.8555 | Val Loss: 24.4338
-----------------------

Epoch 200/5000 | Batch Loss: 19.4874
Epoch 200/5000 | Batch Loss: 1.2545
Epoch 200/5000 | Batch Loss: 0.9539
Epoch 200/5000 | Batch Loss: 6.1679
Epoch 200/5000 | Batch Loss: 2.8587
Epoch 200/5000 | Batch Loss: 1.4066
Epoch 200/5000 | Batch Loss: 1.1153
Epoch 200/5000 | Batch Loss: 5.3491
Epoch 200/5000 | Batch Loss: 1.2724
Epoch 200/5000 | Batch Loss: 1.4673
Epoch 200/5000 | Batch Loss: 2.2667
Epoch 200/5000 | Batch Loss: 1.8871
Epoch 200/5000 | Batch Loss: 2.1099
Epoch 200/5000 | Batch Loss: 2.0010
Epoch 200/5000 | Batch Loss: 6.1723
Epoch 200/5000 | Batch Loss: 1.8207
Epoch 200/5000 | Batch Loss: 2.1544
Epoch 200/5000 | Batch Loss: 3.7278
Epoch 200/5000 | Batch Loss: 1.6103
Epoch 200/5000 | Batch Loss: 2.4014
Epoch 200/5000 | Batch Loss: 1.0533
Epoch 200/5000 | Batch Loss: 2.0887
Epoch 200/5000 | Batch Loss: 1.3791
Epoch 200/5000 | Batch Loss: 1.5914
Epoch 200/5000 | Batch Loss: 2.0676
Epoch 200/5000 | Batch Loss: 2.5217

Epoch 200: Train Loss: 3.0072 | Val Loss: 24.7171
-----------------------

Epoch 250/5000 | Batch Loss: 1.3223
Epoch 250/5000 | Batch Loss: 2.6766
Epoch 250/5000 | Batch Loss: 1.3642
Epoch 250/5000 | Batch Loss: 1.6205
Epoch 250/5000 | Batch Loss: 2.6474
Epoch 250/5000 | Batch Loss: 18.3728
Epoch 250/5000 | Batch Loss: 0.9553
Epoch 250/5000 | Batch Loss: 1.5109
Epoch 250/5000 | Batch Loss: 0.9198
Epoch 250/5000 | Batch Loss: 2.9298
Epoch 250/5000 | Batch Loss: 4.4613
Epoch 250/5000 | Batch Loss: 1.9364
Epoch 250/5000 | Batch Loss: 4.0218
Epoch 250/5000 | Batch Loss: 1.8474
Epoch 250/5000 | Batch Loss: 4.5031
Epoch 250/5000 | Batch Loss: 1.3693
Epoch 250/5000 | Batch Loss: 2.5716
Epoch 250/5000 | Batch Loss: 2.3014
Epoch 250/5000 | Batch Loss: 0.6683
Epoch 250/5000 | Batch Loss: 2.3591
Epoch 250/5000 | Batch Loss: 1.4630
Epoch 250/5000 | Batch Loss: 2.5603
Epoch 250/5000 | Batch Loss: 2.2048
Epoch 250/5000 | Batch Loss: 0.8706
Epoch 250/5000 | Batch Loss: 1.5274
Epoch 250/5000 | Batch Loss: 5.7571

Epoch 250: Train Loss: 2.8747 | Val Loss: 24.2155
-----------------------

Epoch 300/5000 | Batch Loss: 2.8404
Epoch 300/5000 | Batch Loss: 3.0276
Epoch 300/5000 | Batch Loss: 1.2910
Epoch 300/5000 | Batch Loss: 2.3135
Epoch 300/5000 | Batch Loss: 1.8185
Epoch 300/5000 | Batch Loss: 2.2606
Epoch 300/5000 | Batch Loss: 1.7750
Epoch 300/5000 | Batch Loss: 18.6620
Epoch 300/5000 | Batch Loss: 1.1106
Epoch 300/5000 | Batch Loss: 1.5438
Epoch 300/5000 | Batch Loss: 1.2989
Epoch 300/5000 | Batch Loss: 1.1180
Epoch 300/5000 | Batch Loss: 1.5572
Epoch 300/5000 | Batch Loss: 2.1577
Epoch 300/5000 | Batch Loss: 3.0830
Epoch 300/5000 | Batch Loss: 5.0937
Epoch 300/5000 | Batch Loss: 6.2760
Epoch 300/5000 | Batch Loss: 1.2351
Epoch 300/5000 | Batch Loss: 0.8589
Epoch 300/5000 | Batch Loss: 1.9073
Epoch 300/5000 | Batch Loss: 1.2902
Epoch 300/5000 | Batch Loss: 3.6518
Epoch 300/5000 | Batch Loss: 2.8000
Epoch 300/5000 | Batch Loss: 1.4507
Epoch 300/5000 | Batch Loss: 1.2625
Epoch 300/5000 | Batch Loss: 4.2509

Epoch 300: Train Loss: 2.9206 | Val Loss: 25.8104
-----------------------

Epoch 350/5000 | Batch Loss: 1.7618
Epoch 350/5000 | Batch Loss: 2.9396
Epoch 350/5000 | Batch Loss: 1.3936
Epoch 350/5000 | Batch Loss: 1.7611
Epoch 350/5000 | Batch Loss: 7.5534
Epoch 350/5000 | Batch Loss: 0.8988
Epoch 350/5000 | Batch Loss: 1.0791
Epoch 350/5000 | Batch Loss: 1.3169
Epoch 350/5000 | Batch Loss: 1.2385
Epoch 350/5000 | Batch Loss: 1.0932
Epoch 350/5000 | Batch Loss: 2.2586
Epoch 350/5000 | Batch Loss: 5.7458
Epoch 350/5000 | Batch Loss: 1.4038
Epoch 350/5000 | Batch Loss: 19.0653
Epoch 350/5000 | Batch Loss: 0.8051
Epoch 350/5000 | Batch Loss: 1.4942
Epoch 350/5000 | Batch Loss: 1.8926
Epoch 350/5000 | Batch Loss: 2.3094
Epoch 350/5000 | Batch Loss: 1.3546
Epoch 350/5000 | Batch Loss: 2.2894
Epoch 350/5000 | Batch Loss: 0.9084
Epoch 350/5000 | Batch Loss: 1.5230
Epoch 350/5000 | Batch Loss: 1.8930
Epoch 350/5000 | Batch Loss: 5.2118
Epoch 350/5000 | Batch Loss: 4.0898
Epoch 350/5000 | Batch Loss: 1.2682

Epoch 350: Train Loss: 2.8673 | Val Loss: 25.1191
-----------------------

Epoch 400/5000 | Batch Loss: 2.0673
Epoch 400/5000 | Batch Loss: 4.8086
Epoch 400/5000 | Batch Loss: 1.0148
Epoch 400/5000 | Batch Loss: 1.4799
Epoch 400/5000 | Batch Loss: 2.1746
Epoch 400/5000 | Batch Loss: 0.8152
Epoch 400/5000 | Batch Loss: 1.7338
Epoch 400/5000 | Batch Loss: 1.8801
Epoch 400/5000 | Batch Loss: 2.5092
Epoch 400/5000 | Batch Loss: 1.0384
Epoch 400/5000 | Batch Loss: 1.8485
Epoch 400/5000 | Batch Loss: 0.8071
Epoch 400/5000 | Batch Loss: 2.7712
Epoch 400/5000 | Batch Loss: 1.1090
Epoch 400/5000 | Batch Loss: 1.7858
Epoch 400/5000 | Batch Loss: 18.6355
Epoch 400/5000 | Batch Loss: 1.2593
Epoch 400/5000 | Batch Loss: 3.3965
Epoch 400/5000 | Batch Loss: 3.8443
Epoch 400/5000 | Batch Loss: 5.3948
Epoch 400/5000 | Batch Loss: 1.7368
Epoch 400/5000 | Batch Loss: 4.7056
Epoch 400/5000 | Batch Loss: 2.2194
Epoch 400/5000 | Batch Loss: 3.2382
Epoch 400/5000 | Batch Loss: 1.7457
Epoch 400/5000 | Batch Loss: 2.3210

Epoch 400: Train Loss: 2.9362 | Val Loss: 24.8209
-----------------------

Epoch 450/5000 | Batch Loss: 1.8767
Epoch 450/5000 | Batch Loss: 0.8336
Epoch 450/5000 | Batch Loss: 4.9115
Epoch 450/5000 | Batch Loss: 1.8157
Epoch 450/5000 | Batch Loss: 1.1006
Epoch 450/5000 | Batch Loss: 0.6690
Epoch 450/5000 | Batch Loss: 4.1425
Epoch 450/5000 | Batch Loss: 18.2630
Epoch 450/5000 | Batch Loss: 4.1349
Epoch 450/5000 | Batch Loss: 1.8778
Epoch 450/5000 | Batch Loss: 1.1797
Epoch 450/5000 | Batch Loss: 1.6292
Epoch 450/5000 | Batch Loss: 1.5490
Epoch 450/5000 | Batch Loss: 2.5627
Epoch 450/5000 | Batch Loss: 5.9335
Epoch 450/5000 | Batch Loss: 1.7501
Epoch 450/5000 | Batch Loss: 4.7275
Epoch 450/5000 | Batch Loss: 2.5693
Epoch 450/5000 | Batch Loss: 2.0935
Epoch 450/5000 | Batch Loss: 1.2010
Epoch 450/5000 | Batch Loss: 2.3299
Epoch 450/5000 | Batch Loss: 1.0259
Epoch 450/5000 | Batch Loss: 0.6612
Epoch 450/5000 | Batch Loss: 1.2954
Epoch 450/5000 | Batch Loss: 3.4180
Epoch 450/5000 | Batch Loss: 1.8798

Epoch 450: Train Loss: 2.9012 | Val Loss: 26.3375
-----------------------

Epoch 500/5000 | Batch Loss: 1.6097
Epoch 500/5000 | Batch Loss: 1.1252
Epoch 500/5000 | Batch Loss: 2.3034
Epoch 500/5000 | Batch Loss: 1.6457
Epoch 500/5000 | Batch Loss: 3.7301
Epoch 500/5000 | Batch Loss: 1.5605
Epoch 500/5000 | Batch Loss: 2.3998
Epoch 500/5000 | Batch Loss: 0.8202
Epoch 500/5000 | Batch Loss: 0.9508
Epoch 500/5000 | Batch Loss: 1.1846
Epoch 500/5000 | Batch Loss: 1.9413
Epoch 500/5000 | Batch Loss: 5.3706
Epoch 500/5000 | Batch Loss: 1.5084
Epoch 500/5000 | Batch Loss: 1.9821
Epoch 500/5000 | Batch Loss: 1.8976
Epoch 500/5000 | Batch Loss: 2.8207
Epoch 500/5000 | Batch Loss: 1.4719
Epoch 500/5000 | Batch Loss: 3.4781
Epoch 500/5000 | Batch Loss: 1.6398
Epoch 500/5000 | Batch Loss: 3.8690
Epoch 500/5000 | Batch Loss: 19.7119
Epoch 500/5000 | Batch Loss: 0.8777
Epoch 500/5000 | Batch Loss: 3.0325
Epoch 500/5000 | Batch Loss: 1.9067
Epoch 500/5000 | Batch Loss: 3.0171
Epoch 500/5000 | Batch Loss: 1.9433

Epoch 500: Train Loss: 2.8384 | Val Loss: 25.5688
-----------------------

Epoch 550/5000 | Batch Loss: 2.3827
Epoch 550/5000 | Batch Loss: 1.8330
Epoch 550/5000 | Batch Loss: 0.8131
Epoch 550/5000 | Batch Loss: 0.6878
Epoch 550/5000 | Batch Loss: 0.5804
Epoch 550/5000 | Batch Loss: 1.3374
Epoch 550/5000 | Batch Loss: 1.5462
Epoch 550/5000 | Batch Loss: 2.5644
Epoch 550/5000 | Batch Loss: 3.6728
Epoch 550/5000 | Batch Loss: 1.9138
Epoch 550/5000 | Batch Loss: 1.0388
Epoch 550/5000 | Batch Loss: 1.4434
Epoch 550/5000 | Batch Loss: 2.8529
Epoch 550/5000 | Batch Loss: 0.8740
Epoch 550/5000 | Batch Loss: 8.9432
Epoch 550/5000 | Batch Loss: 2.2503
Epoch 550/5000 | Batch Loss: 19.5303
Epoch 550/5000 | Batch Loss: 1.2502
Epoch 550/5000 | Batch Loss: 3.3200
Epoch 550/5000 | Batch Loss: 0.9544
Epoch 550/5000 | Batch Loss: 3.0735
Epoch 550/5000 | Batch Loss: 2.2480
Epoch 550/5000 | Batch Loss: 2.3167
Epoch 550/5000 | Batch Loss: 1.1725
Epoch 550/5000 | Batch Loss: 3.0605
Epoch 550/5000 | Batch Loss: 0.9841

Epoch 550: Train Loss: 2.7940 | Val Loss: 25.1794
-----------------------

Epoch 600/5000 | Batch Loss: 0.9513
Epoch 600/5000 | Batch Loss: 1.4765
Epoch 600/5000 | Batch Loss: 1.3717
Epoch 600/5000 | Batch Loss: 0.9275
Epoch 600/5000 | Batch Loss: 3.0506
Epoch 600/5000 | Batch Loss: 2.9098
Epoch 600/5000 | Batch Loss: 2.2672
Epoch 600/5000 | Batch Loss: 2.2983
Epoch 600/5000 | Batch Loss: 0.8426
Epoch 600/5000 | Batch Loss: 2.4510
Epoch 600/5000 | Batch Loss: 7.1916
Epoch 600/5000 | Batch Loss: 21.7820
Epoch 600/5000 | Batch Loss: 1.3949
Epoch 600/5000 | Batch Loss: 2.0566
Epoch 600/5000 | Batch Loss: 2.1332
Epoch 600/5000 | Batch Loss: 1.8047
Epoch 600/5000 | Batch Loss: 2.3739
Epoch 600/5000 | Batch Loss: 2.2932
Epoch 600/5000 | Batch Loss: 2.4431
Epoch 600/5000 | Batch Loss: 1.1801
Epoch 600/5000 | Batch Loss: 1.3838
Epoch 600/5000 | Batch Loss: 2.0107
Epoch 600/5000 | Batch Loss: 2.7390
Epoch 600/5000 | Batch Loss: 0.7011
Epoch 600/5000 | Batch Loss: 1.1798
Epoch 600/5000 | Batch Loss: 4.0888

Epoch 600: Train Loss: 2.8963 | Val Loss: 25.8204
-----------------------

Epoch 650/5000 | Batch Loss: 1.4236
Epoch 650/5000 | Batch Loss: 2.7329
Epoch 650/5000 | Batch Loss: 1.4716
Epoch 650/5000 | Batch Loss: 2.4261
Epoch 650/5000 | Batch Loss: 1.6644
Epoch 650/5000 | Batch Loss: 2.5823
Epoch 650/5000 | Batch Loss: 2.1153
Epoch 650/5000 | Batch Loss: 2.5979
Epoch 650/5000 | Batch Loss: 1.8151
Epoch 650/5000 | Batch Loss: 5.3014
Epoch 650/5000 | Batch Loss: 0.9624
Epoch 650/5000 | Batch Loss: 4.1019
Epoch 650/5000 | Batch Loss: 1.7468
Epoch 650/5000 | Batch Loss: 1.4375
Epoch 650/5000 | Batch Loss: 2.1585
Epoch 650/5000 | Batch Loss: 2.0150
Epoch 650/5000 | Batch Loss: 1.2744
Epoch 650/5000 | Batch Loss: 2.2827
Epoch 650/5000 | Batch Loss: 1.4344
Epoch 650/5000 | Batch Loss: 3.2990
Epoch 650/5000 | Batch Loss: 0.8384
Epoch 650/5000 | Batch Loss: 2.4978
Epoch 650/5000 | Batch Loss: 18.2267
Epoch 650/5000 | Batch Loss: 1.0805
Epoch 650/5000 | Batch Loss: 2.0244
Epoch 650/5000 | Batch Loss: 5.2482

Epoch 650: Train Loss: 2.8754 | Val Loss: 25.5636
-----------------------

Epoch 700/5000 | Batch Loss: 1.4055
Epoch 700/5000 | Batch Loss: 2.1020
Epoch 700/5000 | Batch Loss: 1.3011
Epoch 700/5000 | Batch Loss: 0.6805
Epoch 700/5000 | Batch Loss: 3.2121
Epoch 700/5000 | Batch Loss: 3.3769
Epoch 700/5000 | Batch Loss: 2.1407
Epoch 700/5000 | Batch Loss: 0.4926
Epoch 700/5000 | Batch Loss: 2.0216
Epoch 700/5000 | Batch Loss: 1.9594
Epoch 700/5000 | Batch Loss: 2.0500
Epoch 700/5000 | Batch Loss: 2.2238
Epoch 700/5000 | Batch Loss: 17.7352
Epoch 700/5000 | Batch Loss: 4.3364
Epoch 700/5000 | Batch Loss: 0.5743
Epoch 700/5000 | Batch Loss: 5.7485
Epoch 700/5000 | Batch Loss: 1.2747
Epoch 700/5000 | Batch Loss: 0.7239
Epoch 700/5000 | Batch Loss: 1.7254
Epoch 700/5000 | Batch Loss: 1.8068
Epoch 700/5000 | Batch Loss: 1.3255
Epoch 700/5000 | Batch Loss: 1.7741
Epoch 700/5000 | Batch Loss: 2.2699
Epoch 700/5000 | Batch Loss: 6.2426
Epoch 700/5000 | Batch Loss: 2.6768
Epoch 700/5000 | Batch Loss: 1.9186

Epoch 700: Train Loss: 2.8115 | Val Loss: 25.3914
-----------------------

Epoch 750/5000 | Batch Loss: 2.2255
Epoch 750/5000 | Batch Loss: 2.0152
Epoch 750/5000 | Batch Loss: 1.7236
Epoch 750/5000 | Batch Loss: 1.5037
Epoch 750/5000 | Batch Loss: 1.8574
Epoch 750/5000 | Batch Loss: 1.7243
Epoch 750/5000 | Batch Loss: 0.7945
Epoch 750/5000 | Batch Loss: 2.7566
Epoch 750/5000 | Batch Loss: 2.1656
Epoch 750/5000 | Batch Loss: 3.2441
Epoch 750/5000 | Batch Loss: 1.0835
Epoch 750/5000 | Batch Loss: 2.9931
Epoch 750/5000 | Batch Loss: 2.8408
Epoch 750/5000 | Batch Loss: 0.9767
Epoch 750/5000 | Batch Loss: 1.7806
Epoch 750/5000 | Batch Loss: 4.3583
Epoch 750/5000 | Batch Loss: 2.1006
Epoch 750/5000 | Batch Loss: 1.9296
Epoch 750/5000 | Batch Loss: 1.2665
Epoch 750/5000 | Batch Loss: 1.1480
Epoch 750/5000 | Batch Loss: 1.4467
Epoch 750/5000 | Batch Loss: 1.5102
Epoch 750/5000 | Batch Loss: 20.4695
Epoch 750/5000 | Batch Loss: 9.5477
Epoch 750/5000 | Batch Loss: 1.6065
Epoch 750/5000 | Batch Loss: 2.4236

Epoch 750: Train Loss: 2.9805 | Val Loss: 25.4163
-----------------------

Epoch 800/5000 | Batch Loss: 2.5753
Epoch 800/5000 | Batch Loss: 4.4885
Epoch 800/5000 | Batch Loss: 1.7824
Epoch 800/5000 | Batch Loss: 2.6345
Epoch 800/5000 | Batch Loss: 17.9528
Epoch 800/5000 | Batch Loss: 3.5006
Epoch 800/5000 | Batch Loss: 3.3799
Epoch 800/5000 | Batch Loss: 2.0742
Epoch 800/5000 | Batch Loss: 2.1691
Epoch 800/5000 | Batch Loss: 3.8025
Epoch 800/5000 | Batch Loss: 1.8049
Epoch 800/5000 | Batch Loss: 1.8451
Epoch 800/5000 | Batch Loss: 0.9707
Epoch 800/5000 | Batch Loss: 1.3032
Epoch 800/5000 | Batch Loss: 0.8898
Epoch 800/5000 | Batch Loss: 2.4997
Epoch 800/5000 | Batch Loss: 2.7113
Epoch 800/5000 | Batch Loss: 1.2992
Epoch 800/5000 | Batch Loss: 1.4160
Epoch 800/5000 | Batch Loss: 1.4669
Epoch 800/5000 | Batch Loss: 1.0063
Epoch 800/5000 | Batch Loss: 2.0487
Epoch 800/5000 | Batch Loss: 1.0022
Epoch 800/5000 | Batch Loss: 4.4094
Epoch 800/5000 | Batch Loss: 2.5340
Epoch 800/5000 | Batch Loss: 2.9053

Epoch 800: Train Loss: 2.8643 | Val Loss: 25.7784
-----------------------

Epoch 850/5000 | Batch Loss: 2.5601
Epoch 850/5000 | Batch Loss: 1.3792
Epoch 850/5000 | Batch Loss: 2.7291
Epoch 850/5000 | Batch Loss: 2.2519
Epoch 850/5000 | Batch Loss: 2.1313
Epoch 850/5000 | Batch Loss: 5.3343
Epoch 850/5000 | Batch Loss: 1.4010
Epoch 850/5000 | Batch Loss: 3.1072
Epoch 850/5000 | Batch Loss: 3.9397
Epoch 850/5000 | Batch Loss: 1.0143
Epoch 850/5000 | Batch Loss: 3.6092
Epoch 850/5000 | Batch Loss: 1.0931
Epoch 850/5000 | Batch Loss: 2.2231
Epoch 850/5000 | Batch Loss: 1.3477
Epoch 850/5000 | Batch Loss: 1.6871
Epoch 850/5000 | Batch Loss: 0.7961
Epoch 850/5000 | Batch Loss: 1.4214
Epoch 850/5000 | Batch Loss: 0.9939
Epoch 850/5000 | Batch Loss: 18.0581
Epoch 850/5000 | Batch Loss: 6.5091
Epoch 850/5000 | Batch Loss: 1.6543
Epoch 850/5000 | Batch Loss: 1.4513
Epoch 850/5000 | Batch Loss: 1.7681
Epoch 850/5000 | Batch Loss: 1.2713
Epoch 850/5000 | Batch Loss: 1.2594
Epoch 850/5000 | Batch Loss: 2.3377

Epoch 850: Train Loss: 2.8203 | Val Loss: 25.6426
-----------------------

Epoch 900/5000 | Batch Loss: 1.0355
Epoch 900/5000 | Batch Loss: 1.1493
Epoch 900/5000 | Batch Loss: 19.9828
Epoch 900/5000 | Batch Loss: 1.7039
Epoch 900/5000 | Batch Loss: 0.4849
Epoch 900/5000 | Batch Loss: 1.2731
Epoch 900/5000 | Batch Loss: 0.7550
Epoch 900/5000 | Batch Loss: 2.4593
Epoch 900/5000 | Batch Loss: 1.5573
Epoch 900/5000 | Batch Loss: 8.4485
Epoch 900/5000 | Batch Loss: 2.1684
Epoch 900/5000 | Batch Loss: 1.7905
Epoch 900/5000 | Batch Loss: 2.3040
Epoch 900/5000 | Batch Loss: 4.3573
Epoch 900/5000 | Batch Loss: 1.2622
Epoch 900/5000 | Batch Loss: 2.6812
Epoch 900/5000 | Batch Loss: 1.2177
Epoch 900/5000 | Batch Loss: 0.6372
Epoch 900/5000 | Batch Loss: 5.2043
Epoch 900/5000 | Batch Loss: 2.2244
Epoch 900/5000 | Batch Loss: 1.7903
Epoch 900/5000 | Batch Loss: 0.9818
Epoch 900/5000 | Batch Loss: 2.6413
Epoch 900/5000 | Batch Loss: 1.9066
Epoch 900/5000 | Batch Loss: 1.7953
Epoch 900/5000 | Batch Loss: 2.0539

Epoch 900: Train Loss: 2.8410 | Val Loss: 26.2657
-----------------------

Epoch 950/5000 | Batch Loss: 3.5962
Epoch 950/5000 | Batch Loss: 6.2330
Epoch 950/5000 | Batch Loss: 2.8777
Epoch 950/5000 | Batch Loss: 2.2319
Epoch 950/5000 | Batch Loss: 1.5893
Epoch 950/5000 | Batch Loss: 1.4126
Epoch 950/5000 | Batch Loss: 0.9514
Epoch 950/5000 | Batch Loss: 1.1563
Epoch 950/5000 | Batch Loss: 0.9197
Epoch 950/5000 | Batch Loss: 1.7616
Epoch 950/5000 | Batch Loss: 1.9990
Epoch 950/5000 | Batch Loss: 6.1332
Epoch 950/5000 | Batch Loss: 3.3018
Epoch 950/5000 | Batch Loss: 1.1222
Epoch 950/5000 | Batch Loss: 2.8614
Epoch 950/5000 | Batch Loss: 17.9403
Epoch 950/5000 | Batch Loss: 1.2524
Epoch 950/5000 | Batch Loss: 2.4256
Epoch 950/5000 | Batch Loss: 1.5356
Epoch 950/5000 | Batch Loss: 1.7102
Epoch 950/5000 | Batch Loss: 1.6581
Epoch 950/5000 | Batch Loss: 1.2477
Epoch 950/5000 | Batch Loss: 3.2104
Epoch 950/5000 | Batch Loss: 1.1327
Epoch 950/5000 | Batch Loss: 2.9056
Epoch 950/5000 | Batch Loss: 0.9399

Epoch 950: Train Loss: 2.8502 | Val Loss: 25.9954
-----------------------

Epoch 1000/5000 | Batch Loss: 1.5085
Epoch 1000/5000 | Batch Loss: 0.9785
Epoch 1000/5000 | Batch Loss: 7.7117
Epoch 1000/5000 | Batch Loss: 1.0635
Epoch 1000/5000 | Batch Loss: 2.1155
Epoch 1000/5000 | Batch Loss: 3.8665
Epoch 1000/5000 | Batch Loss: 2.8658
Epoch 1000/5000 | Batch Loss: 1.9720
Epoch 1000/5000 | Batch Loss: 1.5742
Epoch 1000/5000 | Batch Loss: 1.2417
Epoch 1000/5000 | Batch Loss: 1.9668
Epoch 1000/5000 | Batch Loss: 1.7092
Epoch 1000/5000 | Batch Loss: 2.8858
Epoch 1000/5000 | Batch Loss: 1.7813
Epoch 1000/5000 | Batch Loss: 1.4285
Epoch 1000/5000 | Batch Loss: 2.0567
Epoch 1000/5000 | Batch Loss: 4.0227
Epoch 1000/5000 | Batch Loss: 1.8374
Epoch 1000/5000 | Batch Loss: 20.4696
Epoch 1000/5000 | Batch Loss: 1.7555
Epoch 1000/5000 | Batch Loss: 1.4424

Can you use the above information to create a plot to visualize the learning rate improving? You will need to add a 'standard' GD option also.